import { CompanySettings, ServiceTemplate, Client, Invoice, Quotation } from '../types';

export const DEFAULT_COMPANY_SETTINGS: CompanySettings = {
  companyName: 'AR Web Solutions',
  tagline: 'We Design • We Develop • We Grow',
  phones: ['Aarez Syed – +91 9699700601', 'Raiyan Shaikh – +91 8855802532'],
  email: 'info.arwebsolutions@gmail.com',
  website: 'arwebsolutions.netlify.app',
  address: 'Commercial Complex, Sector 15, Vashi',
  city: 'Navi Mumbai',
  state: 'Maharashtra',
  pinCode: '400703',
  gstNumber: '27AABCU9601R1ZB',

  logoUrl: '', // blank by default or uses stylized AR logo badge
  signatureUrl: '', // blank by default or stylized signature

  defaultGstPercentage: 18,
  defaultCurrency: 'INR',
  defaultCurrencySymbol: '₹',
  invoicePrefix: 'ARWS-2026-',
  quotationPrefix: 'ARWS-QT-2026-',

  bankName: 'HDFC Bank',
  accountHolder: 'AR WEB SOLUTIONS',
  accountNumber: '50200088992211',
  ifsc: 'HDFC0000240',
  upiId: 'info.arwebsolutions@okaxis',

  defaultNotes: 'Thank you for choosing AR Web Solutions.\nWe appreciate your business and look forward to working with you again.',
  defaultTerms: `1. 50% advance payment required before project commencement.
2. Remaining payment to be cleared prior to final source code / website delivery.
3. Includes 1 month free technical maintenance & support post-deployment.
4. Domain registration and server hosting fees are non-refundable.
5. Additional feature revisions beyond agreed scope will be billed separately.`,
};

export const SERVICE_TEMPLATES: ServiceTemplate[] = [
  {
    id: 'tmpl-1',
    name: 'Landing Page',
    description: 'High-converting responsive landing page design with fast load speed and call-to-action sections.',
    suggestedPrice: 15000,
    defaultGst: 18,
  },
  {
    id: 'tmpl-2',
    name: 'Business Website',
    description: 'Corporate multi-page website with dynamic services section, company portfolio, and inquiry forms.',
    suggestedPrice: 35000,
    defaultGst: 18,
  },
  {
    id: 'tmpl-3',
    name: 'Portfolio Website',
    description: 'Personal or agency portfolio website with interactive gallery, project showcases, and contact integration.',
    suggestedPrice: 18000,
    defaultGst: 18,
  },
  {
    id: 'tmpl-4',
    name: 'School Website',
    description: 'School portal with notice board, admission inquiries, academic calendar, and photo gallery.',
    suggestedPrice: 45000,
    defaultGst: 18,
  },
  {
    id: 'tmpl-5',
    name: 'College Website',
    description: 'Comprehensive college portal with department modules, online admission forms, and faculty directory.',
    suggestedPrice: 65000,
    defaultGst: 18,
  },
  {
    id: 'tmpl-6',
    name: 'Hospital Website',
    description: 'Healthcare portal with doctor appointment scheduling, department directory, and emergency contacts.',
    suggestedPrice: 55000,
    defaultGst: 18,
  },
  {
    id: 'tmpl-7',
    name: 'Restaurant Website',
    description: 'Food & beverage website featuring digital menu, table reservation system, and location map.',
    suggestedPrice: 25000,
    defaultGst: 18,
  },
  {
    id: 'tmpl-8',
    name: 'E-Commerce Website',
    description: 'Full online store with product management, shopping cart, payment gateway integration, and order tracking.',
    suggestedPrice: 75000,
    defaultGst: 18,
  },
  {
    id: 'tmpl-9',
    name: 'Real Estate Website',
    description: 'Property listing platform with interactive filters, agent contact cards, and virtual tour embeddings.',
    suggestedPrice: 60000,
    defaultGst: 18,
  },
  {
    id: 'tmpl-10',
    name: 'Travel Website',
    description: 'Tour booking portal with itinerary packages, custom lead forms, and customer reviews.',
    suggestedPrice: 50000,
    defaultGst: 18,
  },
  {
    id: 'tmpl-11',
    name: 'Website Redesign',
    description: 'Modern UI/UX overhaul, mobile responsiveness upgrade, performance optimization, and brand refresh.',
    suggestedPrice: 28000,
    defaultGst: 18,
  },
  {
    id: 'tmpl-12',
    name: 'Hosting',
    description: 'Premium cloud web hosting server with SSL, daily automated backups, and 99.9% uptime SLA (1 Year).',
    suggestedPrice: 8500,
    defaultGst: 18,
  },
  {
    id: 'tmpl-13',
    name: 'Domain Registration',
    description: '.com / .in / .org domain registration & DNS management setup for 1 year.',
    suggestedPrice: 1800,
    defaultGst: 18,
  },
  {
    id: 'tmpl-14',
    name: 'SEO',
    description: 'Comprehensive Search Engine Optimization including technical audit, keyword strategy, and monthly ranking reports.',
    suggestedPrice: 20000,
    defaultGst: 18,
  },
  {
    id: 'tmpl-15',
    name: 'Google Business Profile Setup',
    description: 'Google Maps verification, profile optimization, local citation building, and review integration.',
    suggestedPrice: 6000,
    defaultGst: 18,
  },
  {
    id: 'tmpl-16',
    name: 'Website Maintenance',
    description: 'Monthly security monitoring, content updates, plugin patches, and speed optimization package.',
    suggestedPrice: 12000,
    defaultGst: 18,
  },
  {
    id: 'tmpl-17',
    name: 'SSL Installation',
    description: '256-bit SSL certificate installation, HTTPS redirection, and security headers configuration.',
    suggestedPrice: 2500,
    defaultGst: 18,
  },
  {
    id: 'tmpl-18',
    name: 'Custom Web Application',
    description: 'Bespoke React/Node.js full-stack web application with database architecture, APIs, and custom workflow.',
    suggestedPrice: 120000,
    defaultGst: 18,
  },
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli-1',
    name: 'Vikramaditya Sharma',
    businessName: 'Apex Logistics & Freight',
    email: 'vikram@apexlogistics.in',
    phone: '+91 9820011223',
    gstNumber: '27AAACA1234F1Z8',
    address: 'Plot 42, MIDC Industrial Area, Andheri East',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    pinCode: '400093',
    website: 'apexlogistics.in',
    notes: 'Key client for logistics platform revamp.',
    createdAt: '2026-05-10',
  },
  {
    id: 'cli-2',
    name: 'Dr. Ananya Roy',
    businessName: 'Aura Care Dental Clinic',
    email: 'contact@auracaredental.com',
    phone: '+91 9167234567',
    gstNumber: '27AABCA5678G2Z1',
    address: 'Suite 201, Green Heights, Bandra West',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    pinCode: '400050',
    website: 'auracaredental.com',
    notes: 'Dental appointment booking system.',
    createdAt: '2026-06-01',
  },
  {
    id: 'cli-3',
    name: 'Rajesh Kulkarni',
    businessName: 'Spice & Grill Fine Dining',
    email: 'rajesh@spiceandgrill.in',
    phone: '+91 9819876543',
    gstNumber: '27AACCS9988H1Z3',
    address: '12 Main Road, MG Road Corner',
    city: 'Pune',
    state: 'Maharashtra',
    country: 'India',
    pinCode: '411001',
    website: 'spiceandgrill.in',
    notes: 'Online menu and catering lead site.',
    createdAt: '2026-06-15',
  },
  {
    id: 'cli-4',
    name: 'Pooja Mehta',
    businessName: 'Urban Edge Interior Design',
    email: 'pooja@urbanedgeinteriors.com',
    phone: '+91 9930456789',
    gstNumber: '27AADCU1122K1Z9',
    address: 'Level 4, Trade Centre, BKC',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    pinCode: '400051',
    website: 'urbanedgeinteriors.com',
    notes: 'Luxury interior design portfolio.',
    createdAt: '2026-07-02',
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-1',
    invoiceNumber: 'ARWS-2026-001',
    date: '2026-07-01',
    dueDate: '2026-07-15',
    status: 'Paid',
    currency: 'INR',
    currencySymbol: '₹',
    client: INITIAL_CLIENTS[0],
    services: [
      {
        id: 'srv-101',
        serviceName: 'E-Commerce Website',
        description: 'Full online store with product catalog, cart, Razorpay payment gateway integration.',
        quantity: 1,
        unitPrice: 75000,
        discount: 5000,
        gstPercentage: 18,
        amount: 82600,
      },
      {
        id: 'srv-102',
        serviceName: 'Hosting',
        description: 'Premium Cloud Server with 99.9% Uptime SLA for 1 year.',
        quantity: 1,
        unitPrice: 8500,
        discount: 0,
        gstPercentage: 18,
        amount: 10030,
      },
    ],
    subtotal: 83500,
    discountType: 'fixed',
    discountValue: 5000,
    discountTotal: 5000,
    gstTotal: 14130,
    roundOff: 0,
    grandTotal: 92630,
    advanceReceived: 92630,
    remainingBalance: 0,
    paymentMode: 'UPI',
    bankDetails: {
      bankName: 'HDFC Bank',
      accountHolder: 'AR WEB SOLUTIONS',
      accountNumber: '50200088992211',
      ifsc: 'HDFC0000240',
      upiId: 'info.arwebsolutions@okaxis',
      showPaymentInfoInPrint: true,
    },
    notes: DEFAULT_COMPANY_SETTINGS.defaultNotes,
    termsAndConditions: DEFAULT_COMPANY_SETTINGS.defaultTerms,
    createdAt: '2026-07-01T10:00:00Z',
    updatedAt: '2026-07-01T10:00:00Z',
    createdBy: 'Aarez Syed',
  },
  {
    id: 'inv-2',
    invoiceNumber: 'ARWS-2026-002',
    date: '2026-07-10',
    dueDate: '2026-07-25',
    status: 'Partially Paid',
    currency: 'INR',
    currencySymbol: '₹',
    client: INITIAL_CLIENTS[1],
    services: [
      {
        id: 'srv-201',
        serviceName: 'Hospital Website',
        description: 'Healthcare website with doctor schedules and online appointment request module.',
        quantity: 1,
        unitPrice: 55000,
        discount: 0,
        gstPercentage: 18,
        amount: 64900,
      },
      {
        id: 'srv-202',
        serviceName: 'SEO',
        description: '3 Months initial Local Healthcare SEO campaign.',
        quantity: 1,
        unitPrice: 20000,
        discount: 2000,
        gstPercentage: 18,
        amount: 21240,
      },
    ],
    subtotal: 75000,
    discountType: 'fixed',
    discountValue: 2000,
    discountTotal: 2000,
    gstTotal: 13140,
    roundOff: 0,
    grandTotal: 86140,
    advanceReceived: 43070,
    remainingBalance: 43070,
    paymentMode: 'Bank Transfer',
    bankDetails: {
      bankName: 'HDFC Bank',
      accountHolder: 'AR WEB SOLUTIONS',
      accountNumber: '50200088992211',
      ifsc: 'HDFC0000240',
      upiId: 'info.arwebsolutions@okaxis',
      showPaymentInfoInPrint: true,
    },
    notes: DEFAULT_COMPANY_SETTINGS.defaultNotes,
    termsAndConditions: DEFAULT_COMPANY_SETTINGS.defaultTerms,
    createdAt: '2026-07-10T11:30:00Z',
    updatedAt: '2026-07-10T11:30:00Z',
    createdBy: 'Raiyan Shaikh',
  },
  {
    id: 'inv-3',
    invoiceNumber: 'ARWS-2026-003',
    date: '2026-07-20',
    dueDate: '2026-08-04',
    status: 'Pending',
    currency: 'INR',
    currencySymbol: '₹',
    client: INITIAL_CLIENTS[2],
    services: [
      {
        id: 'srv-301',
        serviceName: 'Restaurant Website',
        description: 'Digital restaurant menu with online table booking and food gallery.',
        quantity: 1,
        unitPrice: 25000,
        discount: 0,
        gstPercentage: 18,
        amount: 29500,
      },
      {
        id: 'srv-302',
        serviceName: 'Google Business Profile Setup',
        description: 'Complete Google Maps & local SEO setup for restaurant locations.',
        quantity: 1,
        unitPrice: 6000,
        discount: 1000,
        gstPercentage: 18,
        amount: 5900,
      },
    ],
    subtotal: 31000,
    discountType: 'fixed',
    discountValue: 1000,
    discountTotal: 1000,
    gstTotal: 5400,
    roundOff: 0,
    grandTotal: 35400,
    advanceReceived: 0,
    remainingBalance: 35400,
    paymentMode: 'UPI',
    bankDetails: {
      bankName: 'HDFC Bank',
      accountHolder: 'AR WEB SOLUTIONS',
      accountNumber: '50200088992211',
      ifsc: 'HDFC0000240',
      upiId: 'info.arwebsolutions@okaxis',
      showPaymentInfoInPrint: true,
    },
    notes: DEFAULT_COMPANY_SETTINGS.defaultNotes,
    termsAndConditions: DEFAULT_COMPANY_SETTINGS.defaultTerms,
    createdAt: '2026-07-20T14:15:00Z',
    updatedAt: '2026-07-20T14:15:00Z',
    createdBy: 'Aarez Syed',
  },
  {
    id: 'inv-4',
    invoiceNumber: 'ARWS-2026-004',
    date: '2026-06-05',
    dueDate: '2026-06-20',
    status: 'Overdue',
    currency: 'INR',
    currencySymbol: '₹',
    client: INITIAL_CLIENTS[3],
    services: [
      {
        id: 'srv-401',
        serviceName: 'Business Website',
        description: 'Interior design studio luxury showcase website.',
        quantity: 1,
        unitPrice: 35000,
        discount: 0,
        gstPercentage: 18,
        amount: 41300,
      },
    ],
    subtotal: 35000,
    discountType: 'fixed',
    discountValue: 0,
    discountTotal: 0,
    gstTotal: 6300,
    roundOff: 0,
    grandTotal: 41300,
    advanceReceived: 10000,
    remainingBalance: 31300,
    paymentMode: 'Bank Transfer',
    bankDetails: {
      bankName: 'HDFC Bank',
      accountHolder: 'AR WEB SOLUTIONS',
      accountNumber: '50200088992211',
      ifsc: 'HDFC0000240',
      upiId: 'info.arwebsolutions@okaxis',
      showPaymentInfoInPrint: true,
    },
    notes: DEFAULT_COMPANY_SETTINGS.defaultNotes,
    termsAndConditions: DEFAULT_COMPANY_SETTINGS.defaultTerms,
    createdAt: '2026-06-05T09:00:00Z',
    updatedAt: '2026-06-05T09:00:00Z',
    createdBy: 'Raiyan Shaikh',
  },
];

export const INITIAL_QUOTATIONS: Quotation[] = [
  {
    id: 'qt-1',
    quotationNumber: 'ARWS-QT-2026-001',
    date: '2026-07-25',
    validUntil: '2026-08-25',
    status: 'Sent',
    currency: 'INR',
    currencySymbol: '₹',
    client: INITIAL_CLIENTS[3],
    services: [
      {
        id: 'srv-q1',
        serviceName: 'Custom Web Application',
        description: 'AR/3D Interior Room Configurator Web Application.',
        quantity: 1,
        unitPrice: 120000,
        discount: 10000,
        gstPercentage: 18,
        amount: 129800,
      },
    ],
    subtotal: 120000,
    discountType: 'fixed',
    discountValue: 10000,
    discountTotal: 10000,
    gstTotal: 19800,
    grandTotal: 129800,
    notes: 'Estimate valid for 30 days from issuance.',
    termsAndConditions: DEFAULT_COMPANY_SETTINGS.defaultTerms,
    createdAt: '2026-07-25T16:00:00Z',
  },
];
